pulp/pulp-clowder-deployments

images/pulp-rpm-ostree-ubi/Containerfile, images/pulp-rpm-ostree-ubi/centos8-base.repo, images/pulp-rpm-ostree-ubi/centos8-powertools.repo, images/pulp-rpm-ostree-ubi/centos8-stream.repo
=> Adds a Pulp UBI based image with pulp-rpm and pulp-ostree plugins

images/assets/pulp-api, images/assets/pulp-common-entrypoint.sh, images/assets/pulp-content, images/assets/pulp-resource-manager, images/assets/pulp-worker, images/assets/readyz.py, images/assets/route_paths.py, images/assets/wait_on_database_migrations.sh, images/assets/wait_on_postgres.py
repo.
So that the images can actually build.
=> Copy images/assets scripts from pulp-oci-images

build_deploy.sh, deploy/clowdapp.yaml, pr_check.sh
=> Fix error with pr-check due to IMAGE_VERSION

build_deploy.sh
=> Uncommented the image building/publishing code.

deploy/clowdapp.yaml
=> Always use the latest version of pulp-web image for now

deploy/clowdapp.yaml
=> Pass S3 settings to pulp settings.

deploy/clowdapp.yaml
This reverts commit d60e5ab7fe9bfbdc20b54ad050e639c2e9392f40.
=> Revert "Fix access to S3"

deploy/clowdapp.yaml
pod/script on the staging environment.
https://i.imgflip.com/2neebf.jpg
=> Do not attempt to create secrets via the generator

deploy/clowdapp.yaml
This might also fix it by switching to a permanent variable.
=> Debug the secret better

deploy/clowdapp.yaml
Sets teh s3-regin in ephemeral. This is only needed while waiting on https://github.com/pulp/pulp-operator/issues/1057
=> Updates operator to the latest alpha 9 release.

deploy/clowdapp.yaml
=> Enable telemetry.

images/assets/pulp-api, images/assets/pulp-content, images/assets/pulp-worker
=> Use pulpcore-api, pulpcore-content, and pulpcore-worker entrypoints

pr_check.sh
=> Specifies image_tag as a parameter

deploy/clowdapp.yaml
=> Adds an ingress for the content app in the ephemeral environment

deploy/clowdapp.yaml
=> Set CONTENT_ORIGIN to the hostname of the ephemeral environment

deploy/clowdapp.yaml
=> Enables TLS for the ingress in ephemeral

Dockerfile, images/assets/add_signing_service.sh, images/assets/pulp-api, images/assets/pulp-content, images/assets/pulp-worker, images/assets/readyz.py, images/assets/set_init_password.sh, images/assets/wait_on_database_migrations.sh, images/assets/wait_on_postgres.py
=> Remove the ENTRYPOINT to make it compatible with pulp-operator.

Dockerfile
=> Copy the missing scripts to the right spot.

pr_check.sh
Hi
test with this to see if this resolves auth issues
Ref: https://github.com/content-services/content-sources-backend/pull/462
=> remove iqe env ephemeral export

deploy/clowdapp.yaml
=> Fix only trying to create secrets on ephemeral

Dockerfile
Also removed pulp-certguard from the image.
closes: #110
=> Set's specific versions for pulpcore and pulp_rpm

Dockerfile, build_deploy.sh, deploy/clowdapp.yaml, pr_check.sh
This service will be deployed to its own namespace.
=> Updates needed for the new Pulp service

deploy/clowdapp.yaml
=> Fix the create-settings-and-ingress pod OOM

deploy/clowdapp.yaml
=> Fix content app not logging

pr_check.sh
=> Fix resources being removed
